"""empty message

Revision ID: 1ee5094c0690
Revises: 
Create Date: 2020-02-21 10:33:02.597820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee5094c0690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solved_puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grid', sa.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solved_puzzles')
    # ### end Alembic commands ###
